version: '3.8'
services:
  juice-shop:
    image: bkimminich/juice-shop
    environment:
      - NODE_ENV=ctf
      - CTF_KEY=squercon
    ports:
      - 3000:3000
  hacker-tooling:
    image: kalilinux/kali-rolling
    command: sleep infinity

#  To run the CTF server locally you can use the below configuration
#  ctf-server:
#    image: ctfd/ctfd
#    ports:
#      - 8000:8000
#    environment:
#      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
#    depends_on:
#      - db
#  db:
#    image: mariadb:10.4.12
#    restart: always
#    environment:
#      - MYSQL_ROOT_PASSWORD=ctfd
#      - MYSQL_USER=ctfd
#      - MYSQL_PASSWORD=ctfd
#      - MYSQL_DATABASE=ctfd
#    volumes:
#      - .data/mysql:/var/lib/mysql
#    # This command is required to set important mariadb defaults
#    command: [ mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0 ]


